config/routes.rb
GavinBlogNew::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root 'chapters#index'
  resources :chapters, only: [:show]

  get '/feed' => 'chapters#feed', as: :feed, :defaults => { :format => 'atom' }

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
	## Banner uploader
	mount_uploader :banner, BannerUploader

	## Make sure that title, body, and slug exist.
	validates_presence_of :title, :body, :slug

	## Makes sure that slug unique and not admin
	validates :slug, uniqueness: true, exclusion: {in: %w(admin)}

	before_validation :generate_slug


	## next, previous, and random_chapter are object methods as it requires
	## a given objects id to know the upcoming chapter object to return
	## To fix readibility, might make this into class method with current id passed.

	## Finds the  next chapter if it exists, if not, returns nil.
	def next
    Chapter.find_by id: self.id+1
	end

	## Finds the previous chapter if it exists, if not, returns nil.
	def previous
		Chapter.find_by id: self.id-1
	end


	## Finds a random chapter
	def random_chapter
		#rand_id = rand(Chapter.count)+1
		#puts rand_id
		## Pluck out ids (returns array of ids)
		chapter_ids = Chapter.pluck(:id)

		## Sample one of them
		rand_id = chapter_ids.sample
		## Keep doing it till its not the same
		while rand_id == self.id
			rand_id = chapter_ids.sample
		end

		Chapter.where("id >= ?", rand_id).first

	end

	## Overides current to_param to just include the title
	def to_param
		slug
	end

	## Generates slug - parameterized title.
	def generate_slug
		self.slug ||= title.parameterize unless title.nil?
	end



end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  #def url_thumb
  #  @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  #end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  #def url_content
  #  url(:content)
  #end
end

app/models/permitted_params.rb
class PermittedParams < Struct.new(:params)#, :user)
  def chapter
    params.require(:chapter).permit(*chapter_attributes)
  end

  def chapter_attributes
    #if user && user.admin?
     # [:name, :sticky]
    #else
      # [:name]
    #end
    [:title, :body, :banner]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def permitted_params
 	 @permitted_params ||= PermittedParams.new(params)#, current_user)
  end
  helper_method :permitted_params
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController

	def index
	end

	def show
	end

	## Provides feed for atom
	## Not conventional
	def feed
	end


private
	## Get every chapter and cache it.
	def chapters
		@chapters ||= Chapter.all
	end
	helper_method :chapters

	## Finds the page by its slug and cache it.
	def chapter
		@chapter ||= Chapter.find_by_slug!(params[:id])
	end
	helper_method :chapter
end

app/helpers/application_helper.rb
module ApplicationHelper
  ## To use twitters hashtags
  include Twitter::Autolink

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Gavin Ching's Story"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end


  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(options)
    gravatar_id = Digest::MD5::hexdigest("gavinchingy@gmail.com")
    sizeInput = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, size: "#{sizeInput}x#{sizeInput}", alt: "gavin", class: "gravatar")
  end


end

app/views/chapters/_comments.html.erb
    <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'gavinchingstory'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    

app/views/chapters/_nav.html.erb
<ul class="button-group round even-3">
	<li>
	<% if chapter.previous %>
		<%= link_to "Previous", chapter.previous, class: "button" %>
	<% else %>
		<a href="#" class="button disabled">Previous</a>
	<% end %>
	</li>

	<li><%= link_to "Random", chapter.random_chapter, class: "button"%></li>

	<li>
	<% if chapter.next %>
		<%= link_to "Next", chapter.next, class: "button"%>
	<% else %>
		<a href="#" class="button disabled">Next</a>
	<% end %>
	</li>
</ul>

app/views/chapters/_tweet.html.erb
<a href="https://twitter.com/share" class="twitter-share-button" data-text="Check out Gavin's new chapter!" data-via="gching" data-hashtags="gavin2013">Tweet</a>

app/views/chapters/index.html.erb
<%# content_for :head, auto_discovery_link_tag(:atom, feed_path) %>

<section id="header-section" class="module parallax header-img">
  <div class="container container-padding">
    <h1>My Story</h1>
    <div class="faded">
      <h2>A detailed book on my "rife" journey.</h2>
      <div class="about-me"><a href="#" data-reveal-id="aboutModal" class="about-me-btn success button radius">Who dat?</a></div>
    </div>
  </div>
</section>

<% chapters.order("created_at DESC").each do |chapter| %>
  <%= link_to chapter_path(chapter) do%>
    <section id="<%=chapter.id%>-section" class="module parallax section-fade" style="background-image: url('<%= chapter.banner_url %>')">

        <div class="container container-padding">
          <h1><%= chapter.id  %></h1>
          <h2 class="faded"><%= chapter.title %></h2>
        </div>
    </section>
  <% end %>
<% end %>

app/views/chapters/show.html.erb
<% provide(:title, "Chapter #{chapter.id}") %>

<!-- Hack for javascript to see which page it it -->
<div id="showMe">
</div>

<section id="<%=chapter.id%>-section" class="module parallax" style="background-image: url('<%= chapter.banner_url %>')">
  <div class="container container-padding">
    <h1><%="Chapter #{chapter.id}"%></h1>
    <h2><%= chapter.title %></h2>
  </div>
</section>

 <div class="row" style="padding-top: 15px;">
    <div class="small-11 small-centered columns">
	    <%= render 'nav', chapter: chapter %>
		<h3>Chapter <%= chapter.id %> - <%= chapter.title %>    <%= render 'tweet' %></h3>
		<h6 class="subheader">Wrote this baby on <%= chapter.created_at.strftime("%B %d, %Y")%></h6>
		<div class="row">
		  <div class="small-11 small-centered columns"><p><%= raw(chapter.body) %></p></div>
		  <br/>
		  <%# auto_link for twitter hashtags %>
		  <div class="small-11 small-centered columns comment-pad">
		  	<%= render 'comments' %>
		  </div>
		</div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
          <meta charset="utf-8" />

          <!-- Uncomment to make IE8 render like IE7 -->
          <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

          <!-- Set the viewport width to device width for mobile -->
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />

          <title><%= full_title(yield(:title)) %></title>

          <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
    <%# yield :head %>
    <link rel="shortcut icon" href="<%=asset_path('favicon.ico')%>" />
  </head>

  <body>
  <%= render 'shared/header' %>

  <%= yield %>

  <%= render 'shared/footer' %>

  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <script src="//platform.twitter.com/widgets.js"></script>
  </body>
</html>

app/views/shared/_about.html.erb
<div id="aboutModal" class="reveal-modal small" data-reveal>
    <div class="row">
	   	 <div class="text-center"><%= gravatar_for size: 100 %></div>
	   	 <br/>
	   	 <h2 class="text-center">Gavin Ching</h2>
	   	 <h4 class="text-center"><i>Explore. Dream. Discover.</i></h4>
	   	 <hr/>
	   	 <p class="text-center"><a href="mailto:gavinchingy@gmail.com?subject=Hi%20Gavin!&amp;body=Insert%20Message%20Here">gavinchingy@gmail.com</a></p>
	   	 <h2 class="text-center">
	   	 <%= link_to 'https://twitter.com/gching' do %>
  			<i class="fi-social-twitter large"></i>
		 <% end %>
	   	 <%= link_to 'https://github.com/gching' do %>
	  		<i class="fi-social-github large"></i>
		 <% end %>
	   	<%= link_to 'http://www.linkedin.com/pub/gavin-ching/3b/878/6b6' do %>
	  		<i class="fi-social-linkedin large"></i>
		<% end %>
		<%= link_to 'https://plus.google.com/+GavinChing' do %>
	  		<i class="fi-social-google-plus large"></i>
		<% end %>
		</h2>
    </div>
    <a class="close-reveal-modal">&#215;</a>
</div>

app/views/shared/_footer.html.erb
  <!-- Footer -->

<footer>
  <div class="container">
    <h4 class='text-center'>Thank you for reading about my rife.</h2>
    <h5 class='text-center subheader'>&#9829; Gavin Ching 2014</h5>
    <h6 class="text-center subheader">Built with love with <a href="http://foundation.zurb.com/">Foundation</a></h6>
    <div class="text-center"><a href="#top" class="button radius up-button">Go back up baby!</a></div>
  </div>
</footer>

app/views/shared/_header.html.erb
<div class="header-fake fixed">
  <div class="container">
    <div class="left">
      <h1>
        <% if current_page?(root_path) %>
          <%= link_to "My Story", '#top'%>
        <% else %>
          <%= link_to "My Story", root_path %>
        <% end %><small>A detailed book on my "rife" journey.   <%= link_to image_tag("feed-icon-28x28.png"), feed_path %></small>
      </h1>
    </div>
    <div class="right" style="padding-top: 15px; padding-right: 5px">
      <a href="#" data-reveal-id="aboutModal" class="about-me-btn success button radius">Who dat?</a>
    </div>
  </div>
<!-- About me button information -->
<%= render 'shared/about' %>
</div>

app/views/shared/_orbit.html.erb
<li>
  <%= image_tag("picture1.jpg", :alt => "pic_1", class: "image-orbit") %>
  <div class="orbit-caption">
    Me with Lionas at NUS in Singapore!
  </div>
</li>